version: 0.1

phases:
  build:
    commandas:
      - npm install
      - npm run webpack

artifacts:
  files:
    - index.html
    - favicon.ico
    - Paulo-Roberto-Francisco-Junior.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js